micronaut:
  application:
    name: keyManagerGrpc

itau:
  url: "http://localhost:9091"
bcb:
  url: "http://localhost:8082"

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/projeto_pix`}
    username: ${JDBC_USER:zup}
    password: ${JDBC_PASSWORD:password}
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}
    database:

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: "update"
        show_sql: "true"